Concise and readable projectConfig modifications
madewithkoji/koji-vcc pull request #3
Opened 2019-09-04 23:32 UTC by X-yn

Nested if condition was removed and repetition of projectConfig[key] has been avoided.
It's possible to mitigate the usage of forEach and filter on line 11 and 12 using reduce() which will be the next PR

2019-09-05 16:12 UTC, sthielen requested changes
Hey! Thanks for putting this together. Added some notes! If it's not too much trouble, want to add the updates using `reduce` to this PR too? I definitely agree that that is the right way forward

2019-09-05 16:12 UTC, sthielen commented on src/tools/writeConfig.js
> +            Array.isArray(configValue) && Array.isArray(fileValue))
I am getting a parser error here -- possibly requires some babel modifications to use this style of assignment?

2019-09-05 16:12 UTC, sthielen commented on src/tools/writeConfig.js
> +         let configValue = projectConfig[key];
Can you check your editorconfig/eslint settings here? Should match indentation style for the rest of the project

2019-09-08 09:38 UTC, X-yn commented
The changes have been made and reduce() has also been included

2019-09-08 19:37 UTC, sthielen commented
Sweet! LGTM :)

2019-09-08 19:37 UTC, merged